configured_endpoints: 53
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/dinari--inc-dash%2Fdinari-e8b292edcdb7d65c7abcde10eb7a31ba2bac9db76ed93fbe42d991ff32a1381f.yml
openapi_spec_hash: 3f2b39965d4678c7afabfdaabf2760fd
config_hash: 5d4200dd4f6195565c3b04ffa79f05b2
